export const PATHS = {
  HOME: '/',
  LOGIN: '/auth',
  ENTRIES: '/entries',
  HOSTELS: '/hostels',
  PROFILE: '/profile',
  RATINGS: '/ratings',
  MANAGE_USERS: '/users',
  DASHBOARD: '/dashboard',
  REGISTER: '/auth/register',
  ADD_HOSTEL: '/hostels/add',
  RESERVATIONS: '/reservations',
  VERIFY_OTP: '/auth/verify-otp',
  RESET_PASSWORD: '/auth/reset-password',
  EDIT_HOSTEL: '/hostels/:hostelID/edit',
  HOSTEL_ROOMS: '/hostels/:hostelID/rooms',
  ROOM: '/hostels/:hostelID/rooms/:roomID',
  FORGOT_PASSWORD: '/auth/forgot-password',
  ADD_HOSTEL_ROOM: '/hostels/:hostelID/rooms/add',
  EDIT_HOSTEL_ROOM: '/hostels/:hostelID/rooms/:roomID/edit'
} as const;
