export default {
  ROOM_IMAGE_KEY: 'roomImage',
  HOSTEL_IMAGE_KEY: 'hostelImage',
  USER_PAYLOAD_KEY: 'userPayload',
  PROFILE_IMAGE_KEY: 'profileImage',
  ACCEPTED_IMAGE_TYPES: '.png, .jpeg, .jpg',
  ENTRY_STATUSES: { CHECK_IN: 'CHECK_IN', CHECK_OUT: 'CHECK_OUT' },
  ROLES: { ADMIN: 'ADMIN', SUPER_ADMIN: 'SUPER_ADMIN', USER: 'USER' },
  RESERVATION_STATUSES: { PENDING: 'PENDING', DECLINED: 'DECLINED', CONFIRMED: 'CONFIRMED' }
};
